### ISSUE TITLE
How to work with strongswan after ipsec SA rekeying? 

### ISSUE THREAD

**Issue by jdkcloud** [xelerance/xl2tpd#190] opened 2020-01-08 06:25 UTC
After ipsec SA rekeying, old SA will be deleted, and the LCP will fail, and the xl2tpd will be restarted

**Comment by shussain** [comment] 2022-10-12 21:18
It seems the issue is with StrongSwan so closing this ticket.

**Closed by shussain** 2022-10-12 21:18 UTC
