### ISSUE TITLE
xl2tpd client: avp is incorrect size.  8 < 10

### ISSUE THREAD

**Issue by duck-rh** [xelerance/xl2tpd#130] opened 2017-06-13 03:44 UTC
There are similar bugs, but using xl2tpd as server, here it is used as client. It worked fine in this area using 1.3.6+dfsg-2 on Debian Jessie but began to fail right after upgrade to 1.3.8+dfsg-1~bpo8+1 (Jessie backports).

Here is the log:
```
Jun 13 12:23:27 MyServer xl2tpd[7683]: xl2tpd version xl2tpd-1.3.8 started on MyServer PID:7683
Jun 13 12:23:27 MyServer systemd[1]: Started LSB: layer 2 tunelling protocol daemon.
Jun 13 12:23:27 MyServer xl2tpd[7683]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
Jun 13 12:23:27 MyServer xl2tpd[7683]: Forked by Scott Balmos and David Stipp, (C) 2001
Jun 13 12:23:27 MyServer xl2tpd[7683]: Inherited by Jeff McAdams, (C) 2002
Jun 13 12:23:27 MyServer xl2tpd[7683]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016
Jun 13 12:23:27 MyServer xl2tpd[7683]: Listening on IP address 0.0.0.0, port 1701
Jun 13 12:23:36 MyServer xl2tpd[7683]: Connecting to host remote.domain.tld, port 1701
Jun 13 12:23:36 MyServer xl2tpd[7683]: Connection established to 123.12.123.123, 1701.  Local: 50365, Remote: 120 (ref=0/0).
Jun 13 12:23:36 MyServer xl2tpd[7683]: Calling on tunnel 50365
Jun 13 12:23:36 MyServer xl2tpd[7683]: Call established with 123.12.123.123, Local: 14779, Remote: 1, Serial: 1 (ref=0/0)
Jun 13 12:23:36 MyServer xl2tpd[7683]: start_pppd: I'm running:
Jun 13 12:23:36 MyServer xl2tpd[7683]: "/usr/sbin/pppd"
Jun 13 12:23:36 MyServer xl2tpd[7683]: "plugin"
Jun 13 12:23:36 MyServer xl2tpd[7683]: "pppol2tp.so"
Jun 13 12:23:36 MyServer xl2tpd[7683]: "pppol2tp"
Jun 13 12:23:36 MyServer xl2tpd[7683]: "7"
Jun 13 12:23:36 MyServer xl2tpd[7683]: "passive"
Jun 13 12:23:36 MyServer xl2tpd[7683]: "nodetach"
Jun 13 12:23:36 MyServer xl2tpd[7683]: ":"
Jun 13 12:23:36 MyServer xl2tpd[7683]: "refuse-pap"
Jun 13 12:23:36 MyServer xl2tpd[7683]: "auth"
Jun 13 12:23:36 MyServer xl2tpd[7683]: "require-chap"
Jun 13 12:23:36 MyServer xl2tpd[7683]: "name"
Jun 13 12:23:36 MyServer xl2tpd[7683]: "user@blah.blah"
Jun 13 12:23:36 MyServer xl2tpd[7683]: "file"
Jun 13 12:23:36 MyServer xl2tpd[7683]: "/etc/ppp/options.l2tp.myconfig"
Jun 13 12:23:36 MyServer xl2tpd[7683]: child_handler : pppd exited for call 1 with code 2
Jun 13 12:23:36 MyServer xl2tpd[7683]: call_close: Call 14779 to 123.12.123.123 disconnected
Jun 13 12:23:36 MyServer xl2tpd[7683]: result_code_avp: avp is incorrect size.  8 < 10
Jun 13 12:23:36 MyServer xl2tpd[7683]: handle_avps: Bad exit status handling attribute 1 (Result Code) on mandatory packet.
Jun 13 12:23:36 MyServer xl2tpd[7683]: Terminating pppd: sending TERM signal to pid 8629
Jun 13 12:23:36 MyServer xl2tpd[7683]: Connection 120 closed to 123.12.123.123, port 1701 (Result Code: expected at least 10, got 8)
```

**Comment by shussain** [comment] 2017-10-16 19:06
This appears to be a duplicate of issue #90

**Comment by duck-rh** [comment] 2017-10-17 04:21
@shussain maybe it is, but please note in this case I'm using xl2tpd as **client**, not server. So it may be a problem in a common code path, but if this check is in two places it has to be fixed twice. Until it is confirmed, please keep it opened.

**Comment by dagelf** [comment] 2017-12-03 07:12
For the record, I set up an L2TP connection to a Mikrotik server device from xl2tpd client and had the same issue - until I added:

```
/ip pool
add name=vpn ranges=172.16.22.100-172.16.22.199
/ppp profile
set [find name=default-encryption] local-address=172.16.22.1 remote-address=vpn

```
To the Mikrotik L2TP server. (Also took me a few minutes to remember that the server command needs an extra "server" parameter to configure: /int l2tp-server server print). My L2TP server uses the default-encryption profile, of course, but needed the pool added. 

Running xl2tpd -D helped a lot, of course.

**Comment by duck-rh** [comment] 2018-04-23 06:47
I'm not in charge of the other's end's configuration, but the information I have is IPs are configured in a RADIUS server and cannot be provided as a pool. In 1.3.6 it still works like a charm but I would like to upgrade to get fixes in later versions.

I tried with 1.3.11 and the problem is not fixed.

**Comment by isikyus** [comment] 2018-05-04 13:01
I'm seeing a similar "avp is incorrect size" error on Ubuntu 17.10, initially with xl2tpd 1.8 installed.

Seeing duck-rh's comment, I tried installing 1.3.6 from source (which I may well have messed up), but I'm still getting the same error:

```
** Message: xl2tpd started with pid 22653
xl2tpd[22653]: setsockopt recvref[30]: Protocol not available
xl2tpd[22653]: Using l2tp kernel support.
xl2tpd[22653]: xl2tpd version xl2tpd-1.3.6 started on Polontar PID:22653
xl2tpd[22653]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
xl2tpd[22653]: Forked by Scott Balmos and David Stipp, (C) 2001
xl2tpd[22653]: Inherited by Jeff McAdams, (C) 2002
xl2tpd[22653]: Forked again by Xelerance (www.xelerance.com) (C) 2006
xl2tpd[22653]: Listening on IP address 0.0.0.0, port 1701
xl2tpd[22653]: get_call: allocating new tunnel for host [SERVER], port 1701.
xl2tpd[22653]: Connecting to host [SERVER], port 1701
xl2tpd[22653]: control_finish: message type is (null)(0).  Tunnel is 0, call is 0.
xl2tpd[22653]: control_finish: sending SCCRQ
xl2tpd[22653]: handle_avps: handling avp's for tunnel 27486, call 0
xl2tpd[22653]: message_type_avp: message type 2 (Start-Control-Connection-Reply)
xl2tpd[22653]: protocol_version_avp: peer is using version 1, revision 0.
xl2tpd[22653]: framing_caps_avp: supported peer frames: sync
xl2tpd[22653]: bearer_caps_avp: supported peer bearers:
xl2tpd[22653]: firmware_rev_avp: peer reports firmware version 1 (0x0001)
xl2tpd[22653]: hostname_avp: peer reports hostname 'RB2011UAS-Primary'
xl2tpd[22653]: vendor_avp: peer reports vendor 'MikroTik'
xl2tpd[22653]: assigned_tunnel_avp: using peer's tunnel 69
xl2tpd[22653]: receive_window_size_avp: peer wants RWS of 4.  Will use flow control.
xl2tpd[22653]: control_finish: message type is Start-Control-Connection-Reply(2).  Tunnel is 69, call is 0.
xl2tpd[22653]: control_finish: sending SCCCN
xl2tpd[22653]: Connection established to [SERVER], 1701.  Local: 27486, Remote: 69 (ref=0/0).
xl2tpd[22653]: Calling on tunnel 27486
xl2tpd[22653]: control_finish: message type is (null)(0).  Tunnel is 69, call is 0.
xl2tpd[22653]: control_finish: sending ICRQ
xl2tpd[22653]: handle_avps: handling avp's for tunnel 27486, call 1441
xl2tpd[22653]: message_type_avp: message type 11 (Incoming-Call-Reply)
xl2tpd[22653]: assigned_call_avp: using peer's call 1
xl2tpd[22653]: control_finish: message type is Incoming-Call-Reply(11).  Tunnel is 69, call is 1.
xl2tpd[22653]: control_finish: Sending ICCN
xl2tpd[22653]: Call established with [SERVER], Local: 1441, Remote: 1, Serial: 1 (ref=0/0)
xl2tpd[22653]: start_pppd: I'm running: 
xl2tpd[22653]: "/usr/sbin/pppd" 
xl2tpd[22653]: "passive" 
xl2tpd[22653]: "nodetach" 
xl2tpd[22653]: ":" 
xl2tpd[22653]: "debug" 
xl2tpd[22653]: "file" 
xl2tpd[22653]: "/var/run/nm-l2tp-ppp-options-0cad1cf0-39f9-458e-a7f9-5f15aff72f40" 
xl2tpd[22653]: "plugin" 
xl2tpd[22653]: "pppol2tp.so" 
xl2tpd[22653]: "pppol2tp" 
xl2tpd[22653]: "7" 
xl2tpd[22653]: handle_avps: handling avp's for tunnel 27486, call 1441
xl2tpd[22653]: message_type_avp: message type 14 (Call-Disconnect-Notify)
xl2tpd[22653]: result_code_avp: avp is incorrect size.  8 < 10
xl2tpd[22653]: handle_avps: Bad exit status handling attribute 1 (Result Code) on mandatory packet.
xl2tpd[22653]: handle_packet: bad AVP handling!
xl2tpd[22653]: network_thread: bad packet
xl2tpd[22653]: call_close: Call 1441 to [SERVER] disconnected
xl2tpd[22653]: handle_avps: handling avp's for tunnel 27486, call 0
xl2tpd[22653]: message_type_avp: message type 4 (Stop-Control-Connection-Notification)
xl2tpd[22653]: result_code_avp: avp is incorrect size.  8 < 10
xl2tpd[22653]: handle_avps: Bad exit status handling attribute 1 (Result Code) on mandatory packet.
xl2tpd[22653]: handle_packet: bad AVP handling!
xl2tpd[22653]: network_thread: bad packet
xl2tpd[22653]: build_fdset: closing down tunnel 27486
xl2tpd[22653]: Terminating pppd: sending TERM signal to pid 22654
xl2tpd[22653]: Connection 69 closed to [SERVER], port 1701 (Result Code: expected at least 10, got 8)
xl2tpd[22653]: build_fdset: closing down tunnel 27486
nm-l2tp[22577] <info>  Terminated xl2tpd daemon with PID 22653.
xl2tpd[22653]: death_handler: Fatal signal 15 received
```

`[SERVER]` is the IP of the MikroTik server I'm trying to connect to.
I'm trying to follow the instructions at https://github.com/nm-l2tp/network-manager-l2tp#issue-with-not-stopping-system-xl2tpd-service, hence the `nm-l2tp` output.

**Comment by dkosovic** [comment] 2018-05-21 11:48
I wonder if the xl2tpd 1.3.6 works and 1.3.11 not working issue is related to the `lock` PPP option issue which triggers the `avp is incorrect size. 8 < 10` error :

* https://wiki.linaro.org/LMG/Kernel/PPP#A.22avp_is_incorrect_size.__8_.3C_10.22_issue

the `unrecognized option 'lock' ` issue was introduced with xl2tpd commit https://github.com/xelerance/xl2tpd/commit/e140bb6a1ab846e4cf548f4dbcdca6a3604248c6 which reorganized how the options are passed to pppd. Note: xl2tpd 1.3.6 and earlier don't have the commit.

**Closed** 2018-05-21 13:59 UTC

**Comment by isikyus** [comment] 2018-07-26 05:33
> [pool settings] 
> To the Mikrotik L2TP server. (Also took me a few minutes to remember that the server command needs an extra "server" parameter to configure: /int l2tp-server server print). My L2TP server uses the default-encryption profile, of course, but needed the pool added.

I don't believe this is the fix for my problem -- we already have a pool set up on the Mikrotik side.
