### ISSUE TITLE
Connection closed due to timeout

### ISSUE THREAD

**Issue by maltalex** [xelerance/xl2tpd#159] opened 2018-09-18 11:32 UTC
Hi

I'm using [hwdsl2's strongswan VPN docker container](https://github.com/hwdsl2/docker-ipsec-vpn-server) which uses `xl2tpd` from debian:strech - version 1.3.12

When connecting from an iPhone (IOS 11/12), the connection always times out a short while after the phone goes to sleep. When the phone wakes up, the tunnel is already deleted and a connection cannot be established. The log looks like this:

```
ipsec-vpn-server | xl2tpd[1]: Call established with X.X.X.X, PID: 677, Local: 36252, Remote: 2706, Serial: 1
ipsec-vpn-server | xl2tpd[1]: Maximum retries exceeded for tunnel 48963.  Closing.
ipsec-vpn-server | xl2tpd[1]: Terminating pppd: sending TERM signal to pid 677
ipsec-vpn-server | xl2tpd[1]: Connection 4 closed to 5.29.30.245, port 49801 (Timeout)
ipsec-vpn-server | xl2tpd[1]: Unable to deliver closing message for tunnel 48963. Destroying anyway.
ipsec-vpn-server | xl2tpd[1]: Can not find tunnel 48963 (refhim=0)
ipsec-vpn-server | xl2tpd[1]: network_thread: unable to find call or tunnel to handle packet.  call = 36252, tunnel = 48963 Dumping.
ipsec-vpn-server | xl2tpd[1]: Can not find tunnel 48963 (refhim=0)
ipsec-vpn-server | xl2tpd[1]: network_thread: unable to find call or tunnel to handle packet.  call = 36252, tunnel = 48963 Dumping.
ipsec-vpn-server | xl2tpd[1]: Can not find tunnel 48963 (refhim=0)
ipsec-vpn-server | xl2tpd[1]: network_thread: unable to find call or tunnel to handle packet.  call = 36252, tunnel = 48963 Dumping.
```

Is there a way to keep the tunnel open for at least a few hours?

/etc/xl2tpd/xl2tpd.conf:

```
[global]
port = 1701

[lns default]
ip range = 192.168.42.10-192.168.42.250
local ip = 192.168.42.1
require chap = yes
refuse pap = yes
require authentication = yes
name = l2tpd
pppoptfile = /etc/ppp/options.xl2tpd
length bit = yes
```

/etc/ppp/options.xl2tpd:
```
+mschap-v2
ipcp-accept-local
ipcp-accept-remote
ms-dns 1.1.1.1
ms-dns 1.0.0.1
noccp
auth
mtu 1280
mru 1280
proxyarp
lcp-echo-failure 4
lcp-echo-interval 30
connect-delay 5000
```

**Comment by hwdsl2** [comment] 2018-09-18 13:09
@maltalex Hello! By design, iOS devices (iPhone/iPad) disconnects WiFi a few minutes after the screen turns off. Because the network disconnected, the “dead peer detection” feature of IPsec will disconnect the VPN tunnel. Refer to dpddelay/dpdaction/dpdtimeout in /etc/ipsec.conf.

Unlike OpenVPN, iOS devices do not have an automatic reconnect feature for IPsec VPN.

**Comment by shussain** [comment] 2018-09-18 17:27
Thank you for the response @hwdsl2 

As such, closing this issue.

**Closed by shussain** 2018-09-18 17:27 UTC
